spring:
  application:
    name: vaultr

  data:
    redis:
      url: ${REDIS_URL}
      enabled: false

  datasource:
    url: jdbc:shardingsphere:classpath:sharding.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

    properties:
      security.protocol: SSL

      ssl.truststore.type: PEM
      ssl.keystore.type: PEM

      ssl.truststore.location: /tmp/ca.pem
      ssl.keystore.location: /tmp/svc.pem

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
  instances:
    api:
      baseConfig: default
    transactionApi:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0s