spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:shardingsphere:absolutepath:/opt/vaultr/sharding.yml}
  kafka:
    properties:
      ssl.truststore.location: /app/tmp/ca.pem
      ssl.keystore.location: /app/tmp/svc.pem
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
